package com.android.recruitment.features.test

data class TestUiState(
    val id: Int = 1,
    val content: String = "",
    var point: Int = 0,
)

var listTest = listOf(
    TestUiState(id = 1, content = "I am the life of the party."),
    TestUiState(id = 2, content = "I don't talk a lot."),
    TestUiState(id = 3, content = "I feel comfortable around people."),
    TestUiState(id = 4, content = "I keep in the background."),
    TestUiState(id = 5, content = "I start conversations."),
    TestUiState(id = 6, content = "I have little to say."),
    TestUiState(id = 7, content = "I talk to a lot of different people at parties."),
    TestUiState(id = 8, content = "I don't like to draw attention to myself."),
    TestUiState(id = 9, content = "I don't mind being the center of attention."),
    TestUiState(id = 10, content = "I am quiet around strangers."),
    TestUiState(id = 11, content = "I get stressed out easily."),
    TestUiState(id = 12, content = "I am relaxed most of the time."),
    TestUiState(id = 13, content = "I worry about things."),
    TestUiState(id = 14, content = "I seldom feel blue."),
    TestUiState(id = 15, content = "I am easily disturbed."),
    TestUiState(id = 16, content = "I get upset easily."),
    TestUiState(id = 17, content = "I change my mood a lot."),
    TestUiState(id = 18, content = "I have frequent mood swings."),
    TestUiState(id = 19, content = "I get irritated easily."),
    TestUiState(id = 20, content = "I often feel blue."),
    TestUiState(id = 21, content = "I feel little concern for others."),
    TestUiState(id = 22, content = "I am interested in people."),
    TestUiState(id = 23, content = "I insult people."),
    TestUiState(id = 24, content = "I sympathize with others' feelings."),
    TestUiState(id = 25, content = "I am not interested in other people's problems."),
    TestUiState(id = 26, content = "I have a soft heart."),
    TestUiState(id = 27, content = "I am not really interested in others."),
    TestUiState(id = 28, content = "I take time out for others."),
    TestUiState(id = 29, content = "I feel others' emotions."),
    TestUiState(id = 30, content = "I make people feel at ease."),
    TestUiState(id = 31, content = "I am always prepared."),
    TestUiState(id = 32, content = "I leave my belongings around."),
    TestUiState(id = 33, content = "I pay attention to details."),
    TestUiState(id = 34, content = "I make a mess of things."),
    TestUiState(id = 35, content = "I get chores done right away."),
    TestUiState(id = 36, content = "I often forget to put things back in their proper place."),
    TestUiState(id = 37, content = "I like order."),
    TestUiState(id = 38, content = "I shirk my duties."),
    TestUiState(id = 39, content = "I follow a schedule."),
    TestUiState(id = 40, content = "I am exacting in my work."),
    TestUiState(id = 41, content = "I have a rich vocabulary."),
    TestUiState(id = 42, content = "I have difficulty understanding abstract ideas."),
    TestUiState(id = 43, content = "I have a vivid imagination."),
    TestUiState(id = 44, content = "I am not interested in abstract ideas."),
    TestUiState(id = 45, content = "I have excellent ideas."),
    TestUiState(id = 46, content = "I do not have a good imagination."),
    TestUiState(id = 47, content = "I am quick to understand things."),
    TestUiState(id = 48, content = "I use difficult words."),
    TestUiState(id = 49, content = "I spend time reflecting on things."),
    TestUiState(id = 50, content = "I am full of ideas."),
)
